import os
import uuid
from pathlib import Path
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor

# Ensure the output folders exist
OUTPUT_DIR = Path(__file__).parent.parent / "ui" / "static" / "decks"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
CHARTS_DIR = Path(__file__).parent.parent / "ui" / "static"
TEMPLATE_PATH = Path(__file__).parent.parent / "ui" / "static" / "templates" / "theme.pptx"

def generate_presentation_deck(title: str, subtitle: str = "Investigation Summary", slides: list[dict] = None) -> str:
    """
    Generates a professional executive PPTX deck with theme and table support.
    
    Args:
        title: Main title of the presentation.
        subtitle: Subtitle or author line.
        slides: List of dictionaries: 
            [{"type": "title|section|content", "title": "...", "bullets": [...], "table_data": [[...]], "chart_filename": "..."}]
    """
    if slides is None:
        slides = [{"type": "content", "title": "Analysis Summary", "bullets": ["No analysis data provided."]}]
    try:
        # Load template if exists, else start fresh
        if TEMPLATE_PATH.exists():
            prs = Presentation(str(TEMPLATE_PATH))
            # Clean up existing slides in template to start fresh
            for _ in range(len(prs.slides)):
                rId = prs.slides._sle[0].rId
                prs.part.drop_rel(rId)
                del prs.slides._sle[0]
        else:
            prs = Presentation()
        
        # 1. Main Title Slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        slide.shapes.title.text = title
        try:
            slide.placeholders[1].text = f"{subtitle}\nGenerated by Fraud Reasoning Engine"
        except:
            pass

        # 2. Process investigative slides
        for s_data in slides:
            s_type = s_data.get("type", "content")
            
            # --- SECTION SLIDE ---
            if s_type == "section":
                section_layout = prs.slide_layouts[2] # Usually Section Header
                slide = prs.slides.add_slide(section_layout)
                slide.shapes.title.text = s_data.get("title", "Phase Summary")
                continue
                
            # --- TITLE SLIDE (Inter-deck titles) ---
            if s_type == "title":
                slide = prs.slides.add_slide(prs.slide_layouts[0])
                slide.shapes.title.text = s_data.get("title", "Investigation Title")
                continue

            # --- STANDARD CONTENT SLIDE ---
            slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(slide_layout)
            
            # Title Anchor
            title_shape = slide.shapes.title
            title_shape.text = s_data.get("title", "Investigation Analysis")
            
            # Narrative (Left Column)
            raw_content = s_data.get("bullets", []) or s_data.get("content", "")
            bullets = [raw_content] if isinstance(raw_content, str) else raw_content
            
            try:
                body_shape = slide.shapes.placeholders[1]
                body_shape.left = Inches(0.5)
                body_shape.top = Inches(1.4)
                body_shape.width = Inches(5.0)
                body_shape.height = Inches(5.5)
                tf = body_shape.text_frame
                tf.word_wrap = True
                
                if bullets:
                    for i, b in enumerate(bullets):
                        if i == 0: p = tf.paragraphs[0]
                        else: p = tf.add_paragraph()
                        p.text = str(b).strip()
                        p.font.size = Pt(16)
                        p.level = 0
            except:
                pass

            # TABLE MODULE (Right or Center if no chart)
            table_data = s_data.get("table_data")
            chart_filename = s_data.get("chart_filename")
            
            if table_data:
                rows = len(table_data)
                cols = len(table_data[0])
                # Position table on right half
                t_left = Inches(5.8)
                t_top = Inches(1.5)
                t_width = Inches(3.8)
                t_height = Inches(0.5 * rows)
                
                table_shape = slide.shapes.add_table(rows, cols, t_left, t_top, t_width, t_height)
                table = table_shape.table
                
                # Style the table
                for r_idx, row in enumerate(table_data):
                    for c_idx, cell_text in enumerate(row):
                        cell = table.cell(r_idx, c_idx)
                        cell.text = str(cell_text)
                        
                        # Professional styling
                        p = cell.text_frame.paragraphs[0]
                        p.font.size = Pt(12)
                        p.alignment = PP_ALIGN.CENTER
                        
                        if r_idx == 0: # Header
                            p.font.bold = True
                            cell.fill.solid()
                            cell.fill.fore_color.rgb = RGBColor(0, 123, 255) # Audit Blue
                            p.font.color.rgb = RGBColor(255, 255, 255)

            # CHART MODULE
            if chart_filename and not table_data: # Table takes priority on right for now if both exist
                img_path = CHARTS_DIR / chart_filename.strip()
                if img_path.exists():
                    slide.shapes.add_picture(str(img_path), Inches(5.8), Inches(1.5), width=Inches(3.8))

        filename = f"report_{uuid.uuid4().hex[:8]}.pptx"
        filepath = OUTPUT_DIR / filename
        prs.save(str(filepath))
        
        return f"<DECK>{filename}</DECK>"
        
    except Exception as e:
        print(f"⚠️ [Deck Skill Error] {e}")
        return f"Error creating presentation: {str(e)}"
