"""
deck_skill.py

Generates a professional PowerPoint presentation deck (.pptx) from structured
slide data. Supports title, section and content slides; bullet narratives,
optional data tables, and optional embedded chart images.
"""

import uuid
import traceback
from copy import deepcopy
from pathlib import Path

from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
from lxml import etree

# ─── Directory constants ────────────────────────────────────────────────────────
OUTPUT_DIR   = Path(__file__).parent.parent / "ui" / "static" / "decks"
CHARTS_DIR   = Path(__file__).parent.parent / "ui" / "static"
TEMPLATE_PATH = Path(__file__).parent.parent / "ui" / "static" / "templates" / "theme.pptx"

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


# ─── Helpers ───────────────────────────────────────────────────────────────────

def _safe_layout(prs: Presentation, index: int):
    """Return slide layout at *index*, falling back to layout 0 if out of range."""
    layouts = prs.slide_layouts
    if index < len(layouts):
        return layouts[index]
    return layouts[0]


def _load_fresh_presentation() -> Presentation:
    """
    Load the branded template and strip every slide from it so we get a clean
    presentation that retains the theme/master.

    Uses the python-pptx slides package drop_rel API to properly remove both
    the relationship and the slide part, avoiding zip duplicate-name warnings.
    """
    if TEMPLATE_PATH.exists():
        prs = Presentation(str(TEMPLATE_PATH))
        # slides._sldIdLst is the <p:sldIdLst> element; iterate a snapshot
        # so we're not mutating the list while walking it.
        slides_pkg = prs.slides
        for sldId in list(slides_pkg._sldIdLst):
            rId = sldId.get("{http://schemas.openxmlformats.org/officeDocument/2006/relationships}id")
            if rId:
                try:
                    slides_pkg._sldIdLst.remove(sldId)
                    slides_pkg.part.drop_rel(rId)
                except Exception:
                    pass
        return prs
    else:
        print("⚠️ [Deck Skill] theme.pptx not found — using blank presentation.")
        return Presentation()


def _add_title_slide(prs: Presentation, title: str, subtitle: str) -> None:
    layout = _safe_layout(prs, 0)
    slide  = prs.slides.add_slide(layout)

    if slide.shapes.title:
        slide.shapes.title.text = title

    # Subtitle placeholder is index 1 in the standard Title layout
    try:
        slide.placeholders[1].text = f"{subtitle}\nGenerated by Fraud Reasoning Engine"
    except (KeyError, IndexError):
        pass


def _add_section_slide(prs: Presentation, s_data: dict) -> None:
    # Layout index 2 is "Section Header" in Office themes; fall back to 0
    layout = _safe_layout(prs, 2)
    slide  = prs.slides.add_slide(layout)
    if slide.shapes.title:
        slide.shapes.title.text = s_data.get("title", "Section")


# ─── Slide geometry constants (widescreen 10" × 7.5") ────────────────────────
_SLIDE_W       = Inches(10.0)
_SLIDE_H       = Inches(7.5)
_TITLE_LEFT    = Inches(0.4)
_TITLE_TOP     = Inches(0.18)
_TITLE_WIDTH   = Inches(9.2)
_TITLE_HEIGHT  = Inches(0.95)
_BODY_TOP      = Inches(1.25)          # content starts here (below title band)
_BODY_BOTTOM   = Inches(7.15)          # leave a small bottom margin
_BODY_HEIGHT   = _BODY_BOTTOM - _BODY_TOP   # 5.9"
_LEFT_PAD      = Inches(0.4)
_COL_GAP       = Inches(0.25)


def _add_title_textbox(slide, text: str) -> None:
    """Add a standalone title text box at fixed coordinates above the content area."""
    txb = slide.shapes.add_textbox(_TITLE_LEFT, _TITLE_TOP, _TITLE_WIDTH, _TITLE_HEIGHT)
    tf  = txb.text_frame
    tf.word_wrap = False
    p = tf.paragraphs[0]
    p.text           = text
    p.font.size      = Pt(28)
    p.font.bold      = True
    p.font.color.rgb = RGBColor(0x1a, 0x23, 0x7e)  # Deep navy


def _add_content_slide(prs: Presentation, s_data: dict) -> None:
    """
    Renders a content slide using a BLANK layout so that no template placeholder
    can conflict with our manually positioned elements.

    All coordinates are absolute, based on a 10" × 7.5" slide canvas:

    ┌─────────────────────────────────────────┐  0.18"
    │  Title text box  (full width, 0.95" h)  │
    ├──────────────────────┬──────────────────┤  1.25"
    │  Bullets (left top)  │  Chart / Table   │
    ├ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─┤   (right col)    │
    │  Narrative (left bot)│                  │
    └──────────────────────┴──────────────────┘  7.15"

    Layout rules:
    - bullets only             → left col full height
    - bullets + narrative      → bullets top ~55%, narrative bottom ~40%
    - chart only               → chart full width under title
    - bullets + chart          → left 4.7", gap 0.25", right 4.8"
    - bullets + table          → left 4.7", gap 0.25", table right
    - bullets + table + chart  → left 4.7", table top-right, chart bottom-right
    """
    bullets        = _normalise_bullets(s_data.get("bullets") or s_data.get("content", ""))
    narrative      = (s_data.get("narrative") or "").strip()
    table_data     = s_data.get("table_data")
    chart_filename = (s_data.get("chart_filename") or "").strip()
    slide_title    = s_data.get("title", "Analysis")

    has_bullets   = bool(bullets)
    has_narrative = bool(narrative)
    has_table     = bool(table_data)
    has_chart     = bool(chart_filename)
    has_right     = has_table or has_chart

    # Always use a blank layout — full positional control, no clashing placeholders
    layout = _safe_layout(prs, 6)   # index 6 = Blank in most Office themes
    slide  = prs.slides.add_slide(layout)

    # Title text box (always explicit, never from template placeholder)
    _add_title_textbox(slide, slide_title)

    # ── Column geometry ──────────────────────────────────────────────────────
    if has_right:
        left_w  = Inches(4.7)
        right_w = Inches(4.8)
        right_l = _LEFT_PAD + left_w + _COL_GAP   # 5.4"
    else:
        left_w  = Inches(9.2)
        right_w = Inches(0)
        right_l = Inches(0)

    # ── Left column: bullets + optional narrative ─────────────────────────────
    _GAP = Inches(0.15)

    if has_bullets and has_narrative:
        # Split left column: bullets get top 55%, narrative gets bottom 40%
        bullet_h    = _BODY_HEIGHT * 0.55
        narrative_top = _BODY_TOP + bullet_h + _GAP
        narrative_h   = _BODY_BOTTOM - narrative_top
        _add_bullet_textbox(slide, bullets, _LEFT_PAD, _BODY_TOP, left_w, bullet_h)
        _add_narrative_textbox(slide, narrative, _LEFT_PAD, narrative_top, left_w, narrative_h)
    elif has_bullets:
        _add_bullet_textbox(slide, bullets, _LEFT_PAD, _BODY_TOP, left_w, _BODY_HEIGHT)
    elif has_narrative:
        # Narrative alone fills the left column
        _add_narrative_textbox(slide, narrative, _LEFT_PAD, _BODY_TOP, left_w, _BODY_HEIGHT)

    # ── Right column ─────────────────────────────────────────────────────────
    if has_table and has_chart:
        # Table at top-right, chart below it
        table_rows = len(table_data)
        table_h    = Inches(0.45 * table_rows + 0.15)
        _add_table(slide, table_data, right_l, _BODY_TOP, right_w)

        chart_top = _BODY_TOP + table_h + Inches(0.2)
        chart_h   = _BODY_BOTTOM - chart_top
        if chart_h > Inches(1.0):
            _embed_chart(slide, chart_filename, right_l, chart_top, right_w, chart_h)

    elif has_table:
        _add_table(slide, table_data, right_l, _BODY_TOP, right_w)

    elif has_chart:
        if has_bullets or has_narrative:
            # Chart fills right column alongside left content
            _embed_chart(slide, chart_filename, right_l, _BODY_TOP, right_w, _BODY_HEIGHT)
        else:
            # No left content → chart takes full width
            _embed_chart(slide, chart_filename, _LEFT_PAD, _BODY_TOP, Inches(9.2), _BODY_HEIGHT)


def _embed_chart(slide, filename: str, left, top, width, height) -> None:
    """Add a chart image to the slide at the given absolute position."""
    img_path = CHARTS_DIR / filename
    if img_path.exists():
        slide.shapes.add_picture(str(img_path), left, top, width=width, height=height)
    else:
        print(f"⚠️ [Deck Skill] Chart not found: {img_path}")


def _normalise_bullets(raw) -> list:
    if not raw:
        return []
    if isinstance(raw, str):
        return [raw] if raw.strip() else []
    return [str(b).strip() for b in raw if str(b).strip()]


def _add_bullet_textbox(slide, bullets: list, left, top, width, height) -> None:
    """Add a plain text box (never a placeholder) with bullet lines at exact coords."""
    txb = slide.shapes.add_textbox(left, top, width, height)
    tf  = txb.text_frame
    tf.word_wrap = True
    for i, b in enumerate(bullets):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        run = p.add_run()
        run.text      = f"▸  {b}"
        run.font.size = Pt(15)


def _add_narrative_textbox(slide, text: str, left, top, width, height) -> None:
    """
    Renders 1-2 paragraph prose below the bullets.
    Uses a slightly smaller, non-bold italic style to visually distinguish
    it from the key bullet findings.
    """
    txb = slide.shapes.add_textbox(left, top, width, height)
    tf  = txb.text_frame
    tf.word_wrap = True

    # Thin top separator line rendered as a single em-dash rule
    sep = tf.paragraphs[0]
    sep_run = sep.add_run()
    sep_run.text      = "─" * 40
    sep_run.font.size = Pt(8)
    sep_run.font.color.rgb = RGBColor(0xB0, 0xB8, 0xC8)

    # Narrative paragraphs (split on double newline if the LLM supplies two)
    paragraphs = [p.strip() for p in text.split("\n\n") if p.strip()]
    if not paragraphs:
        paragraphs = [text.strip()]

    for para_text in paragraphs:
        p = tf.add_paragraph()
        run = p.add_run()
        run.text        = para_text
        run.font.size   = Pt(13)
        run.font.italic = True
        run.font.color.rgb = RGBColor(0x44, 0x44, 0x55)
        p.space_before  = Pt(6)


def _add_table(slide, table_data: list, left, top, width) -> None:
    """Render a styled table on the slide."""
    if not table_data or not table_data[0]:
        return
    rows = len(table_data)
    cols = len(table_data[0])
    row_height = Inches(0.45)
    height     = row_height * rows

    tbl_shape = slide.shapes.add_table(rows, cols, left, top, width, height)
    tbl       = tbl_shape.table

    for r_idx, row in enumerate(table_data):
        for c_idx, cell_text in enumerate(row):
            cell = tbl.cell(r_idx, c_idx)
            cell.text = str(cell_text)

            p = cell.text_frame.paragraphs[0]
            p.font.size  = Pt(12)
            p.alignment  = PP_ALIGN.CENTER

            if r_idx == 0:  # Header row
                p.font.bold = True
                cell.fill.solid()
                cell.fill.fore_color.rgb = RGBColor(0x1a, 0x23, 0x7e)  # Deep navy
                p.font.color.rgb         = RGBColor(0xFF, 0xFF, 0xFF)
            elif r_idx % 2 == 1:  # Alternating row shading
                cell.fill.solid()
                cell.fill.fore_color.rgb = RGBColor(0xE8, 0xEA, 0xF6)  # Light lavender


# ─── Public entry point ────────────────────────────────────────────────────────

def generate_presentation_deck(
    title: str,
    subtitle: str = "Investigation Summary",
    slides: list = None
) -> str:
    """
    Generates a professional executive PPTX deck.

    Args:
        title:    Main presentation title.
        subtitle: Subtitle / author line shown on the cover slide.
        slides:   List of slide dicts:
                  {
                    "type": "title" | "section" | "content",
                    "title": str,
                    "bullets": [str, ...],          # optional
                    "table_data": [[str, ...], ...], # optional
                    "chart_filename": str            # optional
                  }
    Returns:
        A <DECK>filename.pptx</DECK> tag on success, or an error string.
    """
    if slides is None:
        slides = [{"type": "content", "title": "Analysis Summary",
                   "bullets": ["No analysis data provided."]}]
    try:
        prs = _load_fresh_presentation()

        # Cover slide
        _add_title_slide(prs, title, subtitle)

        # Content slides
        for s_data in slides:
            s_type = s_data.get("type", "content").lower().strip()
            if s_type == "section":
                _add_section_slide(prs, s_data)
            elif s_type == "title":
                _add_title_slide(prs, s_data.get("title", ""), "")
            else:
                _add_content_slide(prs, s_data)

        filename = f"report_{uuid.uuid4().hex[:8]}.pptx"
        filepath  = OUTPUT_DIR / filename
        prs.save(str(filepath))
        print(f"✅ [Deck Skill] Saved: {filepath}")
        return f"<DECK>{filename}</DECK>"

    except Exception as e:
        print(f"⚠️ [Deck Skill Error]\n{traceback.format_exc()}")
        return f"Error creating presentation: {str(e)}"
